E_comerce_Inventory.Web/Areas/Inventory/Controllers/ShoppingCartController.cs
using DinkToPdf;
using DinkToPdf.Contracts;
using E_comerce_Inventory.DataAccess.Repository.Interface;
using E_comerce_Inventory.Models.DataModels;
using E_comerce_Inventory.Models.ViewModels;
using E_comerce_Inventory.Utilities;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace E_comerce_Inventory.Web.Areas.Inventory.Controllers
{
    [Area("Inventory")]
    public class ShoppingCartController :Controller
    {
        private readonly IWorkUnit _workUnit;
        private readonly IEmailSender _emailSender;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IConverter _convert;
        [BindProperty]
        public ShoppingCartViewModel ShoppingCartVM { get; set; }

        public ShoppingCartController(IWorkUnit workUnit,IEmailSender emailSender,UserManager<IdentityUser> userManager,IConverter converter)
        {
            _workUnit = workUnit;
            _emailSender = emailSender;
            _userManager = userManager;
            _convert = converter;

        }
        public IActionResult Index()
        {
            var userAplicationId = GetClaim().Value;

            ShoppingCartVM = new ShoppingCartViewModel()
            {
                Order = new Order(),//inicializo la orden
                ShoppingCartList = _workUnit.ShoppingCart.GetAll(sc => sc.UserAplicationId == userAplicationId,addProperties: $"{nameof(Product)}") //todos los productos con sus cantidades
            };
            //sigo inicializando la orden
            ShoppingCartVM.Order.OrderTotal = 0;
            ShoppingCartVM.Order.UserAplication = _workUnit.UserAplication.GetFirst(ua => ua.Id == userAplicationId);

            foreach (var list in ShoppingCartVM.ShoppingCartList)
            {
                //price es una propieda no mapeada en la base de datos
                //De cada carrito voy accediendo a su correspondiente producto asignado y le guerdo el precio en price                
                ShoppingCartVM.Order.OrderTotal += (list.Product.Price * list.Quantity);
            }

            return View(ShoppingCartVM);
        }


        public IActionResult AddProductShoppingCart(int shoppingcartid)
        {
            var shoppingCart = _workUnit.ShoppingCart.GetFirst(sc => sc.Id == shoppingcartid);
            shoppingCart.Quantity++;
            _workUnit.SaveChangesInDb();

            return RedirectToAction(nameof(Index)); //redirijo al index para que vualva a cargar la vista con tododo actualizado

        }
        public IActionResult ReduceProductShoppingCart(int shoppingcartid)
        {
            var shoppingCart = _workUnit.ShoppingCart.GetFirst(sc => sc.Id == shoppingcartid,addProperties: $"{nameof(Product)}");
            if (shoppingCart.Quantity == 1)
            {
                DelteProductOfCart(shoppingCart);

                var numberProducts = _workUnit.ShoppingCart.GetAll(sc => sc.UserAplicationId == shoppingCart.UserAplicationId).ToList().Count(); //cantida de productos que tiene el usuario
                UpdateSesion(numberProducts);
            } else
            {
                shoppingCart.Quantity--;
                _workUnit.SaveChangesInDb();
            }

            return RedirectToAction(nameof(Index));//redirijo al index para que vualva a cargar la vista con tododo actualizado

        }
        public IActionResult DeleteProductOfShoppingCart(int shoppingcartid)
        {
            var shoppingCart = _workUnit.ShoppingCart.GetFirst(sc => sc.Id == shoppingcartid,addProperties: $"{nameof(Product)}");
            DelteProductOfCart(shoppingCart);
            var numberProducts = _workUnit.ShoppingCart.GetAll(sc => sc.UserAplicationId == shoppingCart.UserAplicationId).ToList().Count();//cantida de productos que tiene el usuario       
            UpdateSesion(numberProducts);

            return RedirectToAction(nameof(Index));//redirijo al index para que vualva a cargar la vista con tododo actualizado

        }


        public IActionResult ProceedWithThePayment()
        {

            var userAplicationId = GetClaim().Value;


            ShoppingCartVM = new ShoppingCartViewModel()
            {
                Order = new Order(),//inicializo la orden
                ShoppingCartList = _workUnit.ShoppingCart.GetAll(sc => sc.UserAplicationId == userAplicationId,addProperties: $"{nameof(Product)}") //todos los productos con sus cantidades
            };
            //sigo inicializando la orden
            ShoppingCartVM.Order.OrderTotal = 0;
            ShoppingCartVM.Order.UserAplication = _workUnit.UserAplication.GetFirst(ua => ua.Id == userAplicationId);

            foreach (var list in ShoppingCartVM.ShoppingCartList)
            {
                //price es una propieda no mapeada en la base de datos
                //De cada carrito voy accediendo a su correspondiente producto asignado y le guerdo el precio en price                
                ShoppingCartVM.Order.OrderTotal += (list.Product.Price * list.Quantity);
            }

            ShoppingCartVM.Order.Name = ShoppingCartVM.Order.UserAplication.Name;
            ShoppingCartVM.Order.LastName = ShoppingCartVM.Order.UserAplication.LastName;
            ShoppingCartVM.Order.Country = ShoppingCartVM.Order.UserAplication.Country;

            return View(ShoppingCartVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult ProceedWithThePayment(Order order)
        {
            ShoppingCartViewModel CartVM = LoadViewModelWhitData(order);
            if (!ModelState.IsValid)
            {
                return View(order);
            }

            TempData.Put("datashoppingcartpayment",CartVM); //Con la propiedad [BindProperty] me ahorraba hacer lo del tempData ,
                                                            //porque cuando los valores de una accion pasean a otra por post se mantengan las propiedades   

            return RedirectToAction(nameof(Payment));
        }


        public IActionResult Payment()
        {


            ShoppingCartViewModel CartVM = TempData.Get<ShoppingCartViewModel>("datashoppingcartpayment");
            TempData.Keep("datashoppingcartpayment");
            //el model es valido aca porque se realizo al validacion en la vista anterior
            return View(CartVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Payment(string stripeToken)
        {
            var userAplicationId = GetClaim().Value;
            ShoppingCartVM = new ShoppingCartViewModel()
            {
                Order = new Order(),

            };
            ShoppingCartVM.Order.UserAplication = _workUnit.UserAplication.GetFirst(ua => ua.Id == userAplicationId);
            ShoppingCartVM.ShoppingCartList = _workUnit.ShoppingCart.GetAll(sc => sc.UserAplicationId == userAplicationId,addProperties: $"{nameof(Product)}");


            ShoppingCartVM.Order.OrderState = StateOrder.Pending.ToString();
            ShoppingCartVM.Order.PaymentStatus = StatePayment.Pending.ToString();
            ShoppingCartVM.Order.UserAplicationId = userAplicationId;
            ShoppingCartVM.Order.OrderDate = DateTime.Now;
            ShoppingCartVM.Company = _workUnit.Company.GetFirst();

            ShoppingCartViewModel CartVM = TempData.Get<ShoppingCartViewModel>("datashoppingcartpayment");

            ShoppingCartVM.Order.Address = CartVM.Order.Address;
            ShoppingCartVM.Order.City = CartVM.Order.City;
            ShoppingCartVM.Order.Dni = CartVM.Order.Dni;
            ShoppingCartVM.Order.Phone = CartVM.Order.Phone;
            ShoppingCartVM.Order.PostalCode = CartVM.Order.PostalCode;
            ShoppingCartVM.Order.LastName = CartVM.Order.LastName;
            ShoppingCartVM.Order.Name = CartVM.Order.Name;
            ShoppingCartVM.Order.Country = CartVM.Order.Country;


            _workUnit.Order.Add(ShoppingCartVM.Order);
            _workUnit.SaveChangesInDb();

            foreach (var shoppingCart in ShoppingCartVM.ShoppingCartList)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    ProductId = shoppingCart.ProductId,
                    OrderId = ShoppingCartVM.Order.Id,
                    Price = shoppingCart.Product.Price,
                    Quantity = shoppingCart.Quantity,
                };
                //actualizo el total de la orden por cada producto que recorro de mi carrito
                ShoppingCartVM.Order.OrderTotal += (orderDetail.Price * orderDetail.Quantity);
                //a cada orden formada la guardo en la base de datos
                _workUnit.OrderDetail.Add(orderDetail);
            }

            //borrlo todos los productos de mi carrito ya que se realizo la orden
            _workUnit.ShoppingCart.DeleteRange(ShoppingCartVM.ShoppingCartList);
            // _workUnit.SaveChangesInDb();
            //actualizo la session 
            UpdateSesion(0);

            if (stripeToken != null)

            {
                var options = new Stripe.ChargeCreateOptions
                {
                    Amount = Convert.ToInt32(ShoppingCartVM.Order.OrderTotal * 100),
                    Currency = "usd",
                    Description = "Numero de Orden: " + ShoppingCartVM.Order.Id,
                    Source = stripeToken
                };

                var service = new Stripe.ChargeService();

E_comerce_Inventory.Web/Areas/Inventory/Views/ShoppingCart/Index.cshtml
@model E_comerce_Inventory.Models.ViewModels.ShoppingCartViewModel

<form method="post">
    <br />
    @if (Model.ShoppingCartList.Count() > 0)
    {
      
        <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row ">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Carro de Compras
                        </div>
                        <div class="col-6 text-right">
                            <a asp-area="Inventory" asp-controller="Home" asp-action="Index" class="btn btn-outline-info btn-sm">Seguir Comprando</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @foreach (var item in Model.ShoppingCartList)
                        {
                            <div class="row">
                                <div class="d-none d-lg-block col-lg-1 text-center py-2">
                                    <img src="@item.Product.ImageUrl" class="rounded" width="100" />
                                </div>
                                <div class="col-12 text-sm-center col-lg-6 text-lg-left">
                                    <h5><strong>@item.Product.Description</strong></h5>
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                    <div class="col-4 text-md-right" style="padding-top:5px;">
                                    <h6><strong>@item.Product.Price.ToString("C")<span class="text-muted"> x </span> @item.Quantity </strong></h6>
                                    </div>
                                    <div class="col-6 col-sm-4 col-lg-6">
                                        <div class="float-right mx-1 mt-1">
                                        <a class="btn btn-primary" asp-action="AddProductShoppingCart" asp-route-shoppingcartid="@item.Id">
                                                <i class="bi bi-plus"></i>
                                            </a>
                                        </div>
                                        <div class="float-right mx-1 mt-1">
                                        <a class="btn btn-primary" asp-action="ReduceProductShoppingCart" asp-route-shoppingcartid="@item.Id">
                                                <i class="bi bi-dash"></i>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-2 col-sm-4 col-lg-2 text-right">
                                    <a class="btn btn-outline-danger" asp-action="DeleteProductOfShoppingCart" asp-route-shoppingcartid="@item.Id">
                                                <i class="bi bi-trash3"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <hr />
                        }

                        <div class="row">
                            <div class="col-12 col-md-6 offset-md-6 col-lg-4 offset-lg-8 pr-4">
                                <ul class="list-group">
                                    <li class="list-group-item d-flex justify-content-between bg-light">
                                        <span class="text-info"> Total</span>
                                        <strong class="text-info"> <span id="txtTotalOrden">@Model.Order.OrderTotal.ToString("C")</span></strong>
                                    </li>
                                </ul>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <div class="card-footer row">

                            <div class="col-sm-12 col-lg-4 col-md-6 offset-lg-8 offset-md-6 ">

                            <a asp-area="Inventory" asp-controller="ShoppingCart" asp-action="ProceedWithThePayment" class="btn btn-success form-control">Proceder</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
       
    }

</form>

E_comerce_Inventory.Web/Areas/Inventory/Views/ShoppingCart/Payment.cshtml
@model E_comerce_Inventory.Models.ViewModels.ShoppingCartViewModel
@using Microsoft.Extensions.Options;
@inject IOptions<E_comerce_Inventory.Utilities.StripeSettings> Stripe
@if(Model  != null)
{
    
<form method="post">
    <br />
    <div class="backgroundWhiteBorder">
        <div class="container">
            <div class="card">
                <div class="card-header bg-dark text-light ml-0 row container">
                    <div class="col-6">
                        <i class="fa fa-shopping-cart"></i> &nbsp;
                        Detalles de la Orden
                    </div>
                    <div class="col-6 text-right">
                        <a asp-area="Inventory" asp-controller="ShoppingCart" asp-action="Index" class="btn btn-outline-info btn-sm">Regresar al Carro</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <div class="col-12 col-lg-6 pb-4">
                                <div class="row">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info">Detalles de Envío:</span>
                                    </h4>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Nombre</label>
                                    </div>
                                    <div class="col-9">                                       
                                        <span  class="">@Model.Order.Name</span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Apellido</label>
                                    </div>
                                    <div class="col-9">                                       
                                        <span  class="">@Model.Order.LastName</span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Direccion</label>
                                    </div>
                                    <div class="col-9">                                      
                                        <span  class="">@Model.Order.Address</span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Pais</label>
                                    </div>
                                    <div class="col-9">                                      
                                        <span  class="">@Model.Order.Country</span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Ciudad</label>
                                    </div>
                                    <div class="col-9">                                      
                                        <span  class="">@Model.Order.City</span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Codigo postal</label>
                                    </div>
                                    <div class="col-9">
                                  
                                        <span  class="">@Model.Order.PostalCode</span>
                                    </div>
                                </div>

                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Telefono</label>
                                    </div>
                                    <div class="col-9">                                        
                                        <span  class="">@Model.Order.Phone</span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>DNI</label>
                                    </div>
                                    <div class="col-9">                                    
                                        <span  class="">@Model.Order.Dni</span>
                                    </div>
                                </div>

                            </div>
                            <div class="col-12 col-lg-5 offset-lg-1">
                                <h4 class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="text-info">Productos:</span>
                                </h4>
                                <ul class="list-group mb-3">
                                    @foreach (var item in Model.ShoppingCartList)
                                    {
                                        <li class="list-group-item d-flex justify-content-between">
                                            <div>
                                                <h6 class="my-0">@item.Product.Description</h6>
                                                <small class="text-muted">Cantidad: @item.Quantity</small>
                                            </div>
                                            <span class="text-muted">$ @(item.Product.Price * item.Quantity)</span>
                                        </li>
                                    }

                                    <li class="list-group-item d-flex justify-content-between bg-light">
                                        <strong class="text-info">$@(Model.Order.OrderTotal)</strong>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-12 col-md-8 pt-2">
                            <p style="color:maroon; font-size:14px;">Fecha Estimada de Envío: @DateTime.Now.AddDays(7).ToShortDateString() - @DateTime.Now.AddDays(14).ToShortDateString()</p>
                        </div>
                        <div class="col-12 col-md-4">

                            @{
                                //a stripe hay que mandarselo multiplicado por 100 documentacion
                                var TotalOrderStripe = Model.Order.OrderTotal * 100;
                              
                            }


                                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                    data-key="@Stripe.Value.PublishableKey"
                                    data-amount="@TotalOrderStripe"
                                    data-name="Ecomerce inventory"
                                    data-label="Realizar pedido"
                                    data-description="Compra informatica"
                                    data-locale="auto"
                                    data-allow-remember-me="false"
                                    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                                    >
                                </script>

                                <script>

                                document.getElementsByClassName("stripe-button-el")[0].style.display = "none"
                                </script>
                            <button type="submit" value="Realizar Pedido" class="btn btn-success form-control">Realizar Pedido</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>
} else
{
    <h2 class=" text-center text-bg-light ">Ups!! Ocurrio un error, presione aqui para volver a intentarlo</h2>

    <a asp-action="ProceedWithThePayment" asp-controller="ShoppingCart" class="btn btn-primary text-center">Volver a intentar </a>
}

E_comerce_Inventory.Web/Areas/Inventory/Views/ShoppingCart/ProceedWithThePayment.cshtml
@model E_comerce_Inventory.Models.ViewModels.ShoppingCartViewModel
<form method="post">
    <br />
    <div class="backgroundWhiteBorder">
        <div class="container">
            <div class="card">
                <div class="card-header bg-dark text-light ml-0 row container">
                    <div class="col-6">
                        <i class="fa fa-shopping-cart"></i> &nbsp;
                        Detalles de la Orden
                    </div>
                    <div class="col-6 text-right">
                        <a asp-area="Inventory" asp-controller="ShoppingCart" asp-action="Index" class="btn btn-outline-info btn-sm">Regresar al Carro</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <div class="col-12 col-lg-6 pb-4">
                                <div class="row">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info">Detalles de Envío:</span>
                                    </h4>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Nombres</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Order.Name" type="text" class="form-control" />
                                        <span asp-validation-for="@Model.Order.Name" class="text-danger"></span>

                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Nombres</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Order.LastName" type="text" class="form-control" />
                                        <span asp-validation-for="@Model.Order.LastName" class="text-danger"></span>


                                    </div>
                                </div>                               
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Direccion</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Order.Address" type="text" class="form-control" />
                                        <span asp-validation-for="@Model.Order.Address" class="text-danger"></span>

                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Pais</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Order.Country" type="text" class="form-control" />
                                        <span asp-validation-for="@Model.Order.Country" class="text-danger"></span>

                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Ciudad</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Order.City" type="text" class="form-control" />
                                        <span asp-validation-for="@Model.Order.City" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Codigo postal</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Order.PostalCode" type="text" class="form-control" />
                                        <span asp-validation-for="@Model.Order.PostalCode" class="text-danger"></span>
                                    </div>
                                </div>
                            
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Telefono</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Order.Phone" type="text" class="form-control" />
                                        <span asp-validation-for="@Model.Order.Phone" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>DNI</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Order.Dni" type="text" class="form-control" />
                                        <span asp-validation-for="@Model.Order.Dni" class="text-danger"></span>

                                    </div>
                                </div>

                            </div>
                            <div class="col-12 col-lg-5 offset-lg-1">
                                <h4 class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="text-info">Productos:</span>
                                </h4>
                                <ul class="list-group mb-3">
                                    @foreach (var item in Model.ShoppingCartList)
                                    {
                                        <li class="list-group-item d-flex justify-content-between">
                                            <div>
                                                <h6 class="my-0">@item.Product.Description</h6>
                                                <small class="text-muted">Cantidad: @item.Quantity</small>
                                            </div>
                                            <span class="text-muted">$ @(item.Product.Price * item.Quantity)</span>
                                        </li>
                                    }

                                    <li class="list-group-item d-flex justify-content-between bg-light">                                    
                                        <strong class="text-info">$@(Model.Order.OrderTotal)</strong>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-12 col-md-8 pt-2">
                            <p style="color:maroon; font-size:14px;">Fecha Estimada de Envío: @DateTime.Now.AddDays(7).ToShortDateString() - @DateTime.Now.AddDays(14).ToShortDateString()</p>
                        </div>
                        <div class="col-12 col-md-4">

                            <button type="submit" value="Realizar Pedido" class="btn btn-success form-control">Realizar Pedido</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>