E_comerce_Inventory.Web/Areas/Admin/Controllers/BrandController.cs
using E_comerce_Inventory.DataAccess.Repository.Interface;
using E_comerce_Inventory.Models.DataModels;
using E_comerce_Inventory.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace E_comerce_Inventory.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = DS.Role_Admin)]
    public class BrandController :Controller
    {
        private readonly IWorkUnit _workUnit;
        public BrandController(IWorkUnit workUnit)
        {
            _workUnit = workUnit;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            Brand brand = new();
            if (id == null)
            {
                return View(brand);
            }

            brand = _workUnit.Brand.GetById(id.GetValueOrDefault());

            return View(brand);

        }


        #region API 
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _workUnit.Brand.GetAll() });
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Upsert(Brand brand)
        {
            if (ModelState.IsValid)
            {
                //crando marca
                if (brand.Id == 0)
                {
                    _workUnit.Brand.Add(brand);
                } else
                {
                    _workUnit.Brand.Update(brand);
                }

                _workUnit.SaveChangesInDb();

                return RedirectToAction(nameof(Index));
            }

            return View(brand);

        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var brandDb = _workUnit.Brand.GetById(id);
            if (brandDb == null)
            {
                return Json(new { success = false,message = "Error al borrar la marca" });
            }
            _workUnit.Brand.Delete(brandDb);
            _workUnit.SaveChangesInDb();

            return Json(new { success = true,message = "Marca borrada exitosamente" });
        }
        #endregion
    }
}

E_comerce_Inventory.Web/Areas/Admin/Controllers/CompanyController.cs
using E_comerce_Inventory.DataAccess.Repository.Interface;
using E_comerce_Inventory.Models.DataModels;
using E_comerce_Inventory.Models.ViewModels;
using E_comerce_Inventory.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Data;
using System.IO;
using System.Linq;

namespace E_comerce_Inventory.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = DS.Role_Admin + "," + DS.Role_Inventory)]

    public class CompanyController :Controller
    {
        private readonly IWorkUnit _workUnit;

        private readonly IWebHostEnvironment _hostEnviroment; //para cargar imagenes al directorio

        public CompanyController(IWorkUnit workUnit,IWebHostEnvironment hostEnviroment)
        {
            _workUnit = workUnit;
            _hostEnviroment = hostEnviroment;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var company = _workUnit.Company.GetAll();
            return View(company);
        }


        [HttpGet]
        /*El producto esta relacionado a brand y category, para podes trabajar con
          todos esos datos asociados de ese prouto creamos un ViewModel que seria un DTO
         Un ViewModel no solo trabajara con los datos estaticos, sino que tambien trabajara con las vistas y datos de marca y categoria y no se agregara a nuesra base de datos 
         */
        public IActionResult Upsert(int? id)
        {
            //inicializamos ProductoVM
            CompanyViewModel companyVM = new()
            {
                Company = new Company(),
                StoreList = _workUnit.Store.GetAll().Select((s) => new SelectListItem
                {
                    Text = s.Name,
                    Value = s.Id.ToString(),
                }),//esto es para qeu cuadno lo edite/cree pueda seccionar a que categorias pertence el produrto, y no mandar todos los modelos a la vista


            };

            if (id == null)
                return View(companyVM);//enviamos para crear el nuevo producto

            companyVM.Company = _workUnit.Company.GetById(id.GetValueOrDefault());

            if (companyVM.Company == null)
                return NotFound();


            return View(companyVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Upsert(CompanyViewModel companyVM)
        {
            if (ModelState.IsValid)
            {
                //load image

                string webRoootPath = _hostEnviroment.WebRootPath;//obtiene la ruta del directorio raíz del servidor web.
                var files = HttpContext.Request.Form.Files;//obtiene la colección de archivos que se han enviado al servidor web.
                //contain images
                if (files.Count > 0)// verifico si se han enviado archivos al servidor web.
                {
                    string fileName = Guid.NewGuid().ToString();//genero el nombre de mi archivo con un ID unico
                    var uploads = Path.Combine(webRoootPath,@"img\companies");//combino  los dos tring en la ruta donde se alojaran las imagens en este servidor
                    var extensionFile = Path.GetExtension(files[0].FileName);//Obtengo la extenxion de mi archivo
                    if (companyVM.Company.LogoUrl != null)
                    {
                        //esto es para editar, por ende necesitamso borra la imagen anterior
                        var imgPath = Path.Combine(webRoootPath,companyVM.Company.LogoUrl.TrimStart('\\'));
                        DeleteImage(imgPath);
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads,fileName + extensionFile),FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }
                    companyVM.Company.LogoUrl = @"\img\companies\" + fileName + extensionFile;

                } else
                {
                    //si actualizo el resto de campos menos la imagen
                    if (companyVM.Company.Id != 0)//se esta actualizando
                    {
                        Company companyDB = _workUnit.Company.GetById(companyVM.Company.Id);

                        companyVM.Company.LogoUrl = companyDB.LogoUrl;

                    }
                }


                if (companyVM.Company.Id == 0)
                {
                    _workUnit.Company.Add(companyVM.Company);

                } else
                {
                    _workUnit.Company.Update(companyVM.Company);
                }


                _workUnit.SaveChangesInDb();
                return RedirectToAction(nameof(Index));

            } else //Model invalid
            {
                companyVM.StoreList = _workUnit.Category.GetAll().Select((s) => new SelectListItem
                {
                    Text = s.Name,
                    Value = s.Id.ToString(),
                });

                if (companyVM.Company.Id != 0)//actualizar
                {
                    companyVM.Company = _workUnit.Company.GetById(companyVM.Company.Id);
                }
            }

            return View(companyVM.Company);

        }


        #region API

        [HttpGet]
        public IActionResult GetAll()
        {

            return Json(new { data = _workUnit.Company.GetAll(addProperties: $"{nameof(Store)}") });

        }

        #endregion

        private void DeleteImage(string imgPath)
        {
            if (System.IO.File.Exists(imgPath))//si existe la imagen en este entrorno y en ese directorio, a borro
            {
                System.IO.File.Delete(imgPath);
            }
        }

    }
}

E_comerce_Inventory.Web/Areas/Admin/Controllers/StoreController.cs
using E_comerce_Inventory.DataAccess.Repository.Interface;
using E_comerce_Inventory.Models.DataModels;
using E_comerce_Inventory.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.Messaging;
using System.Data;

namespace E_comerce_Inventory.Web.Areas.Admin.Controllers
{
    //Le indico al controlador el area al que pertenece
    [Area("Admin")]
    [Authorize(Roles = DS.Role_Admin)]

    public class StoreController :Controller
    {
        private readonly IWorkUnit _workUnit;

        public StoreController(IWorkUnit workUnit)
        {
            _workUnit = workUnit;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Store store = new Store();
            if (id == null)
            {
                //Entonces es un insert , si es asi le envio a la vista el modelo store vacio
                return View(store);
            }
            //si No entro al if entocne se esta queriendo actualizar, entoces a mi store vacia le asigno la store que estan queriendo modificar
            store = _workUnit.Store.GetById(id.GetValueOrDefault());
            if (store == null)
            {
                //si no encontro ninguna store mando un notFound
                return NotFound();
            }

            //si encontro la store la envio a la vista
            return View(store);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //recibo una store del submit del formualri oque viaja por post a este metodo, de la vista Upsert.cshtml
        public IActionResult Upsert(Store store)
        {
            //pregunto si el modelo es valido , es decir si no hubo errores en nuestra pagina
            if (ModelState.IsValid)
            {
                //creando store
                if (store.Id == 0)
                {
                    _workUnit.Store.Add(store);
                } else
                {
                    //actualizar store
                    _workUnit.Store.Update(store);
                }
                _workUnit.SaveChangesInDb();
                //reutn View index
                return RedirectToAction(nameof(Index));
            }
            //return UPSERT view with the model like this
            return View(store);

        }

        #region API
        [HttpGet]
        public IActionResult GetAll()
        {
            //get all stores
            var all = _workUnit.Store.GetAll();
            //return all stores in Json format
            return Json(new { data = all });
        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var store = _workUnit.Store.GetById(id);
            if (store == null)
            {
                //no se encontro la store
                return Json(new { success = false,message = "Error al borrar tienda" });
            }
            _workUnit.Store.Delete(store);
            _workUnit.SaveChangesInDb();

            return Json(new { success = true,message = "Tienda borrada exitosamente" });
        }

        #endregion
    }
}

E_comerce_Inventory.Web/Areas/Admin/Controllers/UserController.cs
using E_comerce_Inventory.DataAccess.Data;
using E_comerce_Inventory.DataAccess.Repository.Interface;
using E_comerce_Inventory.Models.DataModels;
using E_comerce_Inventory.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net.Sockets;

namespace E_comerce_Inventory.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = DS.Role_Admin)]

    public class UserController :Controller
    {
        private readonly IWorkUnit _workUnit;
        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db,IWorkUnit workUnit)
        {
            _db = db;
            _workUnit = workUnit;
        }
        public IActionResult Index()
        {
            return View();
        }


        #region API
        [HttpGet]

        public IActionResult GetAll()
        {

            var users = from u in _db.UsersAplication
                        join r in _db.UserRoles
                        on u.Id equals r.UserId
                        join rl in _db.Roles
                        on r.RoleId equals rl.Id
                        select new { user = u,role = rl.Name };

            return Json(new { data = users,});
        }


        [HttpPost]

        public IActionResult BlockUnblok([FromBody] string id)
        {
            var user = _db.UsersAplication.FirstOrDefault(u => u.Id == id);

            if (user == null)
            {
                return Json(new { success = false,message = "Error de Usuario" });
            }
            if (user.LockoutEnd != null && user.LockoutEnd > DateTime.Now)
            {
                user.LockoutEnd = DateTime.Now;
            } else
            {
                user.LockoutEnd = DateTime.Now.AddYears(200);
            }
            _db.SaveChanges();
            return Json(new { success = true,message = "Operacion exitosa" });
        }
        #endregion
    }
}

E_comerce_Inventory.Web/Views/Shared/_ButtonsAddAndReturnPartial.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Crear</button>
    </div>
    <div class="col">
       @* No detallo el controller , ya que es una vista parcial y va a trabajar con el controlador en el que se encuentre en ese momento*@
        <a asp-action="Index" class="btn btn-success form-control">Regresar</a>
    </div>
</div>

E_comerce_Inventory.Web/Views/Shared/_ButtonsUpdateAndReturnPartial.cshtml
@*esta vista va a recibir el Id , y para indicar eso en el modelo le indico que el un int *@
@model int 
@*ahroa en el boton indico asp-route para que pueda recibir un parametro, asp-route-id es solo un nombre *@
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Actualizar</button>
    </div>
    <div class="col">
        @* No detallo el controller , ya que es una vista parcial y va a trabajar con el controlador en el que se encuentre en ese momento*@
        <a asp-action="Index" class="btn btn-success form-control">Regresar</a>
    </div>
</div>

E_comerce_Inventory.Web/Views/Shared/_Layout.cshtml
@using E_comerce_Inventory.Utilities;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor httpContectAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -Tecno Productos</title>
   @* si quiesiera modo dark y white tendria que crear una claase  que tenga los nomrbe de los archivos entonces cuando los cambie cambie la ruta al archivo de estilos*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />   
    @*icons*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    @*Styles tables*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    @*Jquery calendar*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    @*notifications*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    @*Sweet alert css*@
    <link href="lib/limonte-sweetalert2/sweetalert2.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary  border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="white-space:nowrap">Tecno Productos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(DS.Role_Admin) || User.IsInRole(DS.Role_Inventory))
                        {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Contenido
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        @if(User.IsInRole(DS.Role_Admin))
                                        {
                                             <a class="dropdown-item" asp-area="Admin" asp-controller="Store" asp-action="Index">Tiendas</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Compania</a>
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categorias</a>
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="Brand" asp-action="Index">Marcas</a>                                                              
                                        }
                                    @if (User.IsInRole(DS.Role_Admin) || User.IsInRole(DS.Role_Inventory))
                                    {
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Productos</a>
                                    }
                                    </div>
                                </li>
                        }
                          @if (User.IsInRole(DS.Role_Admin))
                        {
                                <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Usuario
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Usuarios</a>
                            
                                        </div>
                                 </li>
                        }
                        @if (User.IsInRole(DS.Role_Admin) || User.IsInRole(DS.Role_Inventory))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Inventario
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Inventory" asp-controller="Inventory" asp-action="Index">Stock</a>
                                </div>
                            </li>
                        }
                        @if(httpContectAccessor.HttpContext.Session.GetInt32(DS.ssShoppingCart)!=null)
                        {
                            //si es distina de null indica que hay usuario conectado y que la session esta llena
                            <li class="" style="color:white">
                                <a asp-area="Inventory" asp-controller="ShoppingCart" asp-action="Index"  class="nav-link">
                                    @{
                                        var numberOfProduct = httpContectAccessor.HttpContext.Session.GetInt32(DS.ssShoppingCart); //guardo el valor de la cantidad de productos que hay en el carro
                                        //&nbsp esto es un espacio
                                    }
                                    <i class="bi bi-cart-fill rotate-180"></i> &nbsp; (@numberOfProduct)
                                </a>
                            </li>
                        } else //en caso de que no este llena
                        {
                            <li>
                                <a href="#" class="nav-link">
                                    <i class="bi bi-cart-fill rotate-180"></i> &nbsp; (0)
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary text-white-50">
        <div class="container">
            &copy; 2023 - E_comerce_Inventory.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.2/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables.net/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="/lib/limonte-sweetalert2/sweetalert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>